config/routes.rb
Rails.application.routes.draw do
  # shallow nesting
  resources :reviews, only: %i[destroy]

  resources :restaurants do # 7 CRUD actions for restaurants
    # prefixes all the routes with /restaurants/:id
    resources :reviews, only: %i[new create] # nested resource

    collection do
      # get '/restaurants/top', to: 'restaurants#top'
      get :top
      # get :worst
      # get :your_location
    end

    member do
      # get '/restaurants/:id/chef', to: 'restaurants#chef', as: :restaurant_chef
      get :chef
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews # restaurant.reviews
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # review.restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy chef ]

  # GET /restaurants/:id/chef
  def chef
    # @restaurant = Restaurant.find(params[:id])
    @chef_name = @restaurant.chef_name
  end

  # GET /restaurants/top
  def top
    # SELECT * FROM restaurants WHERE ...
    @restaurants = Restaurant.where(rating: 4..)
  end

  # GET /restaurants
  def index
    # SELECT * FROM restaurants
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity # 422
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy!
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # new_restaurant_review GET    /restaurants/:restaurant_id/reviews/new(.:format) reviews#new
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  # restaurant_reviews POST   /restaurants/:restaurant_id/reviews(.:format)     reviews#create
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])

    @review = Review.new(review_params) # { content: '...' }
    @review.restaurant = @restaurant

    if @review.save # only returns true / false
      redirect_to restaurant_path(@restaurant)
    else
      # renders the /views/reviews/new.html.erb with a 422 error code
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /reviews/:id
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeyondCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= restaurant.rating %>
  </p>

</div>

app/views/restaurants/chef.html.erb
<h2><%= @restaurant.name %>'s chef 👨‍🍳</h2>

<h3><%= @chef_name %></h3>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%#= render 'restaurant', restaurant: restaurant %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>


<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<h2>Reviews</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %>
      <%= link_to 'Delete', review_path(review), data: { turbo_method: 'delete' } %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %>

<div>
  <%= link_to 'Show chef information', chef_restaurant_path(@restaurant) %> |
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>

  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/restaurants/top.html.erb
<h2>Top restaurants</h2>

<ul>
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>

<!-- POST /restaurants/:restaurant_id/reviews/new (restaurant_reviews_path) -->
<!-- POST /reviews/new (reviews_path) -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%#= f.association :restaurant %>
  <%= f.submit %>
<% end %>